### ISSUE TITLE
Ability to customise placeholder text

### ISSUE THREAD

**Issue by jackiboy** [Mobius1/Vanilla-DataTables#7]
Hi @Mobius1. Love your library! I will be using this in production. I am wondering if you could add the ability to define placeholder text when you are defining your options for a data table.

I would like to customise the following text for a certain table that searches a list of websites.

So instead of the following for example:

- Search...
- No rows found
- Showing 1 to 1 of 1 rows

I would like to do:

- Search Websites...
- No Websites found
- Showing 1 to 1 of 1 Websites

Thanks,
Jack

**Comment by Mobius1** [comment]
I'd be more than happy to implement these options in the next release. Should be done in the next day or so.

**Comment by jackiboy** [comment]
Brilliant, Thank you!

**Comment by Mobius1** [comment]
Customization implemented. See the [docs](http://mobius.ovh/docs/vanilla-datatables/pages/options#labelsobject)

**Comment by jackiboy** [comment]
Mate you are a star. Thanks!

**Comment by Mobius1** [comment]
No problem!

Due to an error on our end, the wrong commit got pushed to the master branch. Please use [v1.0.6](https://github.com/Mobius1/Vanilla-DataTables/releases/tag/1.0.6) as [v1.0.5](https://github.com/Mobius1/Vanilla-DataTables/releases/tag/1.0.5) is broken. Check the docs for updates as well.

Karl.

**Comment by jackiboy** [comment]
@Mobius1 Forgot to get back to you. Yeah I noticed :-) works great, thanks again for your quick response!
